-- GORM AutoMigrate creates the initial schema at startup. This file documents the managed migration boundary.
-- Tables: categories, products, suppliers, offers, price_histories, favorites, price_alerts, budgets,
-- purchase_orders, purchase_order_items.
-- purchase_orders carries a composite unique index (user_id, idempotency_key) for idempotent submission.
-- offers.available_stock is the remaining supply decremented atomically when a purchase order succeeds.
